import { test, expect, type WebSocketRoute } from '@playwright/test';
import { enterFixtureSession } from './fixture-session';
import { installationFixture } from './installation-fixture';
import { waitForFixtureBudget } from './fixture-budget';

test.beforeEach(waitForFixtureBudget);
test('normalizes speech before Messenger and submission; editable rules persist and typed text stays literal', async ({ page, context }, info) => {
  await context.grantPermissions(['microphone']);
  await installationFixture(page, { recognition: 'deepgram' });
  await page.addInitScript(() => {
    localStorage.setItem('vc2:speech', JSON.stringify({ greeting: false, audioCues: false, keepAwake: false }));
    localStorage.setItem('vc2:speaker-muted', 'true');
  });
  const sockets: WebSocketRoute[] = [], turns: string[] = [];
  await page.routeWebSocket(url => url.pathname === '/api/audio' && url.searchParams.get('kind') === 'stt', socket => {
    sockets.push(socket); socket.send(JSON.stringify({ type: 'ready', sampleRate: 16000 }));
  });
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/turns')) turns.push(request.postDataJSON().text); });
  const emit = (text: string, final = false) => sockets.at(-1)!.send(JSON.stringify({ type: 'stt', text, started: !final, final, turnComplete: final }));
  const openSettings = () => page.getByRole('button', { name: 'Open settings' }).click();
  const save = async () => { await page.getByRole('button', { name: 'Save preferences', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); };
  const closeSettings = () => page.getByRole('button', { name: 'Close Make yourself at home', exact: true }).click();
  const composer = page.getByRole('textbox', { name: 'Message NorthPointe' });
  await enterFixtureSession(page);
  await openSettings();
  await expect(page.getByLabel('As transcribed 1', { exact: true })).toHaveValue('north point');
  await expect(page.getByLabel('Preferred spelling 1', { exact: true })).toHaveValue('NorthPointe');
  await expect(page.getByLabel('Apply transcript rule 1 to', { exact: true })).toHaveValue('name');
  await closeSettings();
  await page.getByRole('button', { name: 'Wake NorthPointe', exact: true }).click();
  await expect(page.locator('.orb-stage.phase-listening')).toBeVisible();
  await page.getByRole('button', { name: /Conversation\s*\d/ }).click();
  emit('Ask north point about the north point of the map.');
  await expect(composer).toHaveValue('Ask NorthPointe about the north point of the map.');
  emit('Ask north point about the north point of the map.', true);
  await expect.poll(() => turns.at(-1)).toBe('Ask NorthPointe about the north point of the map.');
  await expect(page.locator('.orb-stage.phase-listening')).toBeVisible();
  emit('We worship at north point and then visit the north point of the map.');
  await expect(composer).toHaveValue('We worship at NorthPointe and then visit the north point of the map.');
  emit('The church is near the north point.');
  await expect(composer).toHaveValue('The church is near the north point.');
  emit('I am going to north point.');
  await expect(composer).toHaveValue('I am going to north point.');
  emit('Hey north point, show me the north point on the map.');
  await expect(composer).toHaveValue('Hey NorthPointe, show me the north point on the map.');
  emit('Hey north point, show me the north point on the map.', true);
  await expect.poll(() => turns.at(-1)).toBe('Hey NorthPointe, show me the north point on the map.');
  await expect(page.locator('.orb-stage.phase-listening')).toBeVisible();
  await openSettings();
  await page.getByLabel('Preferred spelling 1', { exact: true }).fill('NorthPointe Church');
  await page.getByRole('button', { name: 'Add transcript rule', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Save preferences', exact: true })).toBeDisabled();
  await page.getByLabel('As transcribed 3', { exact: true }).fill('Jev');
  await page.getByLabel('Preferred spelling 3', { exact: true }).fill('JEV');
  await page.getByLabel('As transcribed 1', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('transcript-normalization-settings.png') });
  await save(); await page.reload(); await openSettings();
  await expect(page.getByLabel('Preferred spelling 1', { exact: true })).toHaveValue('NorthPointe Church');
  await expect(page.getByLabel('Apply transcript rule 1 to', { exact: true })).toHaveValue('name');
  await expect(page.getByLabel('Preferred spelling 3', { exact: true })).toHaveValue('JEV');
  await closeSettings();
  await page.getByRole('button', { name: /Conversation\s*\d/ }).click();
  await page.getByRole('switch', { name: 'Auto mode' }).click();
  await expect(page.locator('.orb-stage.phase-listening')).toBeVisible();
  emit('Ask north point and Jev.', true);
  await expect.poll(() => turns.at(-1)).toBe('Ask NorthPointe Church and JEV.');
  await expect(page.locator('.orb-stage.phase-listening')).toBeVisible();
  await page.getByRole('switch', { name: 'Auto mode' }).click();
  await composer.fill('Typed north point and Jev.');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect.poll(() => turns.at(-1)).toBe('Typed north point and Jev.');
  await expect(page.locator('.orb-stage.phase-thinking')).toHaveCount(0);
  await openSettings();
  for (let index = 3; index >= 1; index--) await page.getByRole('button', { name: `Remove transcript rule ${index}`, exact: true }).click();
  await save(); await page.reload(); await openSettings();
  await expect(page.getByText('No rules. Speech text will keep its transcribed spelling.', { exact: true })).toBeVisible();
  await closeSettings();
  await page.getByRole('button', { name: /Conversation\s*\d/ }).click();
  await page.getByRole('switch', { name: 'Auto mode' }).click();
  await expect(page.locator('.orb-stage.phase-listening')).toBeVisible();
  emit('Ask North Point.', true);
  await expect.poll(() => turns.at(-1)).toBe('Ask North Point.');
  await expect(page.locator('.orb-stage.phase-listening')).toBeVisible();
  await page.getByRole('switch', { name: 'Auto mode' }).click();
  await composer.fill('Typed North Point and Jev.');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect.poll(() => turns.at(-1)).toBe('Typed North Point and Jev.');
});
